---
# handlers file for graphite-api-influxdb
- name: restart graphite-api
  service: name=graphite-api state=restarted

- name: restart icinga2
  service: name=icinga2
           state=restarted
           enabled=yes
