---

- name: Get Icinga2 Apt Key for Ubuntu OS family
  apt_key: url='http://packages.icinga.org/icinga.key'
       state=present

- name: Get Icinga2 Apt Repos for Ubuntu OS family
  apt_repository: repo='deb http://packages.icinga.org/ubuntu icinga-trusty main'
       state=present

- name: Install Icinga2 IDO module
  apt: name=icinga2-ido-mysql
       update_cache=yes
       state=latest

- name: Create a Database for Icinga2
  mysql_db: name={{ icinga2_web2_db }}
            state=present
  register: icinga_web2_db

- name: Create Icinga Database User and configure Grants
  mysql_user: name={{ icinga2_web2_db }}
              password={{ icinga2_web2_db_pass }}
              state=present
              priv="{{ icinga2_web2_db_user }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import the IDO Schema on Icinga Web Database
  mysql_db: name={{ icinga2_web2_db }}
            state=import
            target={{ icinga2_web_mysql_schema }}

- name: Configure Icinga2 Ido Mysql Feature
  template: src=ido-mysql.conf.j2
            dest={{ icinga2_ido_mysql_conf }}
            backup=yes
            owner=nagios
            group=nagios
            mode=0755

- name: Install Icinga Web2
  apt: name=icingaweb2
       state=latest
  tags: icinga2-ansible-web2-ui-install

- name: Create a Database for Icingaweb2
  mysql_db: name={{ icinga_web_db }}
            state=present

- name: Create Icinga Database for WEB and configure Grants
  mysql_user: name={{ icinga_web_db }}
              password={{ icinga_web_pass }}
              state=present
              priv="{{ icinga_web_user }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import the MySQL Schema on Icinga Web Database
  mysql_db: name={{ icinga_web_db }}
            state=import
            target={{ icinga2_web_schema }}

- name: Create user
  shell: echo "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '\$1\$hn2ZAGRl\$TKzZQeGImiCkiTN9eVMYU0');" | mysql -u root icingaweb2

- name: Enable Icinga2 Ido Mysql Feature
  command: "icinga2 feature enable ido-mysql"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2

- name: Enable Icinga2 command Feature
  command: "icinga2 feature enable command"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2

- name: Create group icingaweb2
  group: name=icingaweb2 state=present

- name: Change ownet for command
  user: name=nagios
    state=present
    groups="www-data"

- name: Change ownet for icingaweb2
  user: name=icingaweb2
    state=present
    groups="www-data"

- name: Install additional php components
  apt: name={{ item }} state=present
  with_items:
  - php5-imagick
  - php5-gd
  - php5-json
  - php5-intl
 
- name: PHP | Set timezone
  lineinfile: state=present backup=yes create=yes dest={{ item }} regexp='^date\.timezone =' insertafter='^;date\.timezone =' line='date.timezone = UTC'
  with_items:
  - /etc/php5/cli/php.ini
  - /etc/php5/apache2/php.ini
  - /etc/php5/fpm/php.ini

- name: Icinga Web2 Installation finished
  debug: msg="Now generate a token with 'icingacli setup token create' and go at http://IP//icingaweb2/setup to continue the installation"
  tags: icinga2-ansible-web2-ui-install
