---
# defaults file for icinga2-ansible-no-ui

icinga2_key: "http://packages.icinga.org/icinga.key"
icinga2_debmon_key: "http://debmon.org/debmon/repo.key"

icinga2_deb_repos:
 - { repo: "deb http://packages.icinga.org/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main" }
 - { repo: "deb-src http://packages.icinga.org/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main" }
icinga2_debmon_repo: "deb http://debmon.org/debmon debmon-{{ ansible_distribution_release }} main"

icinga2_pkg:
 - { package: "icinga2" }
 - { package: "nagios-plugins" }

req_pkg:
 - { package: "gpg" }

icinga2_main_conf: "/etc/icinga2/icinga2.conf"
icinga2_conf_d: "/etc/icinga2/conf.d"
